DROP TABLE IF EXISTS Observations;
DROP TABLE IF EXISTS Anonymous_users;
DROP TABLE IF EXISTS Projects;

CREATE TABLE Projects (
    project_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    class_id INTEGER NOT NULL,
    teacher_id INTEGER NOT NULL,
    project_code VARCHAR(250) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description VARCHAR(250) NOT NULL,
    directions TEXT NOT NULL,
    form_definition JSON NOT NULL,
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Observations (
    obs_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    project_id INTEGER NOT NULL,
    anon_user_id INTEGER NOT NULL,
    data JSON NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Anonymous_users (
    anon_user_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    token VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);